### ISSUE TITLE
Docker内パッケージに関する質問

### ISSUE THREAD

**Issue by 5ym** [mirakc/mirakc#1391]
いつも開発ありがとうございます
一点質問なのですが、Docker内にpcscdとlibaribb25がないためB-CASカードでのEpgstationなどでスクランブルを解除した状態で利用できないのですが、何か意図があって同梱していないのでしょうか
お手数をおかけして申し訳ありませんが、回答のほどいただけると幸いです。

**Comment by masnagam** [comment]
意図的にそうしていますし，今後も追加することはありません．

**Comment by 5ym** [comment]
回答ありがとうございます
追加で申し訳ないのですが、Dockerでスクランブル解除して利用する場合のベストプラクティス等ありますでしょうか
重ね重ねお手数おかけして申し訳ありませんがよろしくお願いいたします

**Comment by masnagam** [comment]
申し訳ありませんが，私から言えることは何もありません．
