### ISSUE TITLE
I currently have the following tuners. Will they be supported? DTA-2131B(Dektec), DTA-2139C(Dektec), Wintv quardHD

### ISSUE THREAD

**Issue by castinglife** [mirakc/mirakc#1853]
DTA-2131B(Dektec)
DTA-2139C(Dektec)
Wintv quardHD(Hauppauge)

This is Korea. I would like to know if I can record ATSC [QAM | 8VSB] signal.

Is it possible to use it with mirakcrun and mirakc?

**Comment by masnagam** [comment]
mirakc (and also mirakurun) does not directly open any tuner devices. instead, it spawns a command to open a tuner device: https://github.com/mirakc/mirakc/blob/main/docs/config.md#tuners

in mirakc, you can specify a [`mustach`](https://mustache.github.io/) template string in `tuners[].command` and several template parameters are available in the template string.

i'm not familiar with ATSC, but maybe its data format is different from ISDB. therefore, you cannot use mirakc and mirakurun for ATSC data stream without modification.

unlike mirakurun, mirakc does not process ts stream directly. mirakc uses [mirakc-arib](https://github.com/mirakc/mirakc-arib) for processing ts streams, but mirakc-arib does not support ATSC. if you create a program which behaves like `mirakc-arib` for ATSC data stream, you can specify it in `config.yml`. search `mirakc-arib` in https://github.com/mirakc/mirakc/blob/main/docs/config.md#configuration.
