### ISSUE TITLE
衛星が全く受信できない

### ISSUE THREAD

**Issue by lkfejleene** [mirakc/mirakc#198]
user@TV:~/tv-recorder$ uname -a
Linux TV 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
チューナ：DD MaxM4
ドライバ：https://github.com/DigitalDevices/dddvb/archive/0.9.37.zip

主題の通り、今回のmirakc の Updateから衛星がチャンネルスキャンもなにもできなくなりました。
地上波はチューナの仕様通り問題なく動作しております。

epg:
  cache-dir: /var/lib/mirakc/epg

server:
  addrs:
    - http: 0.0.0.0:40772
    - unix: /var/run/mirakurun/mirakurun.sock

channels:
  - name: 'ＮＨＫＥテレ１大阪'
    type: 'GR'
    channel: '13'
    
  - name: 'ＮＨＫＢＳ１101'
    type: 'BS'
    channel: 'BS15_0'
    services: [101]

tuners:
  - name: MaxM4_0
    types:
      - GR
      - BS
      - CS
    command: dvbv5-zap -a 0 -c /etc/mirakc/dvbv5_channels_isdb.conf -r -P {{{channel}}} -o -
    
filters:
  decode-filter:
    command: arib-b25-stream-test

コンソール：
mirakc        | 2021-04-22T18:02:32.560528802+09:00 DEBUG mirakc_core::command_util: dvbv5-zap#125: ERROR    frequency 1317.84MHz (tune freq 1317.84MHz) is out of LNBf Japan 110BS/CS LNBf range 

ご確認を願えますでしょうか？
よろしくおねがいします

**Comment by masnagam** [comment]
@lkfejleene
申し訳ありませんが，再現環境がないためこちらでは解析できません．自力で解析してください．

エラーを見る限りではdvbv5-zapで問題が発生しているように見えます．すでにログレベルはdebugのようなので，以下のように実行したコマンドがログに残っているはずです．

```
2021-04-22T15:37:39.538015+09:00 DEBUG mirakc_core::command_util: tuner#0.0: Spawned 76891: `curl -fsSL http://mirakc1:40772/api/channels/GR/27/stream`
```

まずは，期待通りのコマンドになっているのか確認してください．期待通りのコマンドになっていない場合，mirakcの不具合である可能性があります．期待するコマンドとの違いをレポートしていただければ，こちらで確認可能です．

期待通りのコマンドを実行しているのにエラーになっている場合は，そのコマンドを直接コンソールから実行してみてください．dockerコンテナーで動かしている場合は，`docker exec`などを使ってコマンドをコンテナー内で実行してください．もし，直接コマンドを実行しても同じエラーが発生するなら，それはmirakcの不具合ではありません．

**Comment by lkfejleene** [comment]
ありがとうございます。
こちらで出来る限りの実験をしてみたいと思います。

**Comment by masnagam** [comment]
すみませんがお願いします．

どうしても使っているチューナー機器やコマンドの関係から環境依存で解析できないものがあるんです．

[rr](https://rr-project.org/)じゃないですが，子プロセスの動作を記録し，それを模倣できるようなツールがあれば（もしくは作れば）いいのでしょうが，そこまでは至っていません．

チューナーコマンドは基本stdoutのみなので，出力したデータをタイムスタンプ付き（コマンド起動時からオフセット値）で保存しておいて，これを再生するスクリプトを書くのは難しくなさそうですが，TSが記録されるのでこれを再現確認用データとしてアップロードすることができないのです．．

**Comment by masnagam** [comment]
オープンのままにしておくので，質問などあれば随時ここに書き込んでください．

**Comment by collelog** [comment]
元々当方にEPGStationの番組表が表示されないとのIssueがあり、その際のやり取りで把握しているlkfejleeneさんの事象を以下にまとめておきます。
（当件は地上波の番組表が表示されたのでIssueはclose）

1)トラブル事象
mirakc 1.17.2-alpine カスタムイメージ + [TVTest + Bon_mirakc.dll / EPGStation V1]
・TVTestでGR、BS視聴：OK
・EPG関連ジョブによるservicesファイル生成：NG

2)上記を解決するために、mirakcのバージョンを変更
mirakc main-alpine カスタムイメージ + [TVTest + Bon_mirakc.dll / EPGStation V1]
（変化点はmirakcのバージョンのみ。Alpine Linux、dvbv5-zap（apkコマンドによるインストール）のバージョンは変化なし）
・TVTestでGR視聴：OK
・TVTestでBS視聴：NG
・EPG関連ジョブによるservicesファイル生成（GR分）：OK
・EPG関連ジョブによるservicesファイル生成（BS分）：NG ※チューナーコマンドのエラーログ出力
・コンテナ内でチューナーコマンドを実行したら録画ファイルが正常出力
　（チューナーコマンドのエラーはコンソールに表示されない←？）

**Comment by masnagam** [comment]
@lkfejleene 
参考にならないかもしれませんが
https://mevius.5ch.net/test/read.cgi/avi/1573547529/679-n

dvbv5-zapがエラー発生源なので，以下の可能性があります．

1. mirakcから実行しているdvbv5-zapコマンドに誤りがあり，config.ymlに指定した通りのコマンドが実行されていない
    * https://github.com/mirakc/mirakc/issues/198#issuecomment-824734792 に書いたように，ログで実行されたコマンドを確認
2. mirakcはconfig.ymlに指定されたとおりにdvbv5-zapコマンドを実行しているが，dvbv5-zapでエラーが発生している
    * 高確率でdvbv5-zapの使い方の間違い
        * dvbv5_channels_isdb.confや指定したオプションが正しいのか確認
    * dvbv5-zapが利用するデバイスファイルがコンテナーにマップされていない
        * エラー内容から考えて，この可能性は低いように見えます

**Comment by lkfejleene** [comment]
config.ymlの channel: の数値が一桁の場合、頭に'0'をつけることで解決しました。
しょーもないオチで申し訳無いです。。。

[例]
dvbv5_channels_isdb.conf
   [BS01_0]
　　～略～

config.yml
[正]
  - name: 'ＢＳ朝日１'
    type: 'BS'
    channel: 'BS01_0'
    services: [151]

[誤]
  - name: 'ＢＳ朝日１'
    type: 'BS'
    channel: 'BS1_0'
    services: [151]


あと、チャンネルスキャン中に気がついたのですが、今回のコミットから（？）SERVICE_SPLIT=1 な動きをしてました。
現在運用中の BonDriver_mirakc.ini が以下です。

[GLOBAL]
SERVER_HOST="192.168.0.9"
SERVER_PORT=40772

; B25(1=enable)
DECODE_B25=1

; Priority(0=Low Priority)
PRIORITY=0

; Service Split(1=enable)
SERVICE_SPLIT=0

この運用中の BonDriver_mirakc.ini を削除し、新規に作成してもTVTest(0.9.0)は同じ動きをします。

**Comment by masnagam** [comment]
@lkfejleene 
解決したようで何よりです．

> config.ymlの channel: の数値が一桁の場合、頭に'0'をつけることで解決しました。

エラーのログから気付きにくい問題なのであれば，できるmirakcの[チューナー設定](https://mirakc.github.io/dekiru-mirakc/config/tuners.html)で言及しておいても良いかもしれません．

検証環境のある人が検証済みの内容を記述したほうがよいので，もし時間が取れるようならぜひ追記してPull Requestを送ってください．
難しければこちらで追記します．

> あと、チャンネルスキャン中に気がついたのですが、今回のコミットから（？）SERVICE_SPLIT=1 な動きをしてました。

[epgdatacapbon/BonDriver_mirakc](epgdatacapbon/BonDriver_mirakc) で`SERVICE_SPLIT`を[検索](https://github.com/epgdatacapbon/BonDriver_mirakc/search?q=SERVICE_SPLIT)してみましたが見つかりませんでした．
どこかのタイミングで削除されたのかもしれません．

**Comment by lkfejleene** [comment]
Pull Requestの方は一寸難しいです。申し訳無いです。
では、主題の 「衛星が～」の件は解決しましたので、本稿はcloseさせて頂いてよろしいでしょうか？

また、SERVICE_SPLITの件はBonDriver_mirakcさんマターでよろしいですか？

**Comment by collelog** [comment]
当原因はdvbv5-zapコマンドのconfファイルとchannel指定のマッピング崩れと理解しましたので、もし言及する場合はそこが問題ないかの注意喚起をするレベルになるかもしれませんね

**Comment by masnagam** [comment]
@lkfejleene 了解です．ではこちらで追記しておきます．本件closeします．

@collelog そうですね．そのように書くことにします．
