### ISSUE TITLE
ドキュメントの多言語化

### ISSUE THREAD

**Issue by ghost** [mirakc/mirakc#206]
現在、ドキュメントは日本語でしか書かれていないものと、英語でしか書かれていないものがあります。
これは読者に日英両言語の読解を要求するので、あまり好ましくないと思います。
多言語化した上で、それぞれの言語に翻訳したり、(将来的にプルリクがあれば)他の言語にも対応できるようにしてはどうでしょうか。

現在、https://mirakc.github.io/dekiru-mirakc/ は日本語のみです。
一方、https://github.com/mirakc/mirakc/tree/main/docs は英語のみです。

**Comment by masnagam** [comment]
もともとmirakcでは英語のみを使用しており，できるmirakcのみが例外です．一人で開発している事情もあり，ソフトウェアツールの説明を省略してもソースを参照して自力で問題を解決できるような人のみをターゲットとして公開していました．開発者が一人しかいなので初歩的な質問に答えられるだけの時間がないためです．

私はドキュメントを翻訳することを止めませしPRも喜んで受け付けますが，それをメンテナンスすることを私に期待しないでください．必要としている人自身がそれをメンテナンスすることを私は望んでいます．

できるmirakcは[空気録学電子版](https://medium.com/chinachu/c98v-mirakc-cde04fb67531)に掲載するために作成されたという歴史的経緯があり日本語で書かれています．こちらも翻訳することを止めたりしませんし，PRは歓迎します．
