### ISSUE TITLE
Dockerを使わないでインストールする方法についてドキュメントを整備する

### ISSUE THREAD

**Issue by hamach-boop** [mirakc/mirakc#207]
標準はDockerでいいと思いますが、オプションとしてDockerを使わない方法について言及してもいいのではないでしょうか。

**Comment by masnagam** [comment]
Dockerfileに全ての手順を書いてあるため，ドキュメントは作成しません．

ドキュメントを作成すると，Dockerfileとドキュメントの療法をメンテナンス必要があります．可能な限りメンテナンス工数を減らしたいということもあり，ドキュメントは作成しません．
