### ISSUE TITLE
fix!: name case inconsistency

### ISSUE THREAD

**Issue by masnagam** [mirakc/mirakc#2074]
json files contain camel case and snake case (this is default case) names, but those should be camel case in JSON.

**Comment by masnagam** [comment]
there is no way to specify the case for each data format (JSON, YAML, etc.).

a workaround in my mind is like this (but i have not tried yet at this point):

```rust
#[derive(Clone, Debug, Deserialize, Serialize)]
struct Data {
  ...
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all_fields = "camelCase")]
struct DataInJson(Data);

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all_fields = "kebab-case")]
struct DataInYaml(Data);
```

this probably works in many cases, but not a perfect solution.
for example, enum variant names will be converted in the specified case even if attributes affecting enum variants are not specified.

**Comment by kounoike** [comment]
https://github.com/mirakc/mirakc/pull/2073#issuecomment-2509675929

```
let parsed = match parse_config() {
    Ok(parsed) => parsed,
    Err(ParseError) => {
        convert_config(config_file_path);
        parse_config()
    },
    Err(e) => Err(e)
}
```

こんな感じになってると、失敗したときだけ変換処理が走って良さそうに思いました。convert_config()では型を気にせず単純にcase変換だけを行うイメージです。
（あんまり使っている人いなそうですけど）ファイルを直接読み書きして何かやってる人には影響あるので十分なアナウンスとバージョンの検討は必要そうですね。

**Comment by masnagam** [comment]
> こんな感じになってると、失敗したときだけ変換処理が走って良さそうに思いました。convert_config()では型を気にせず単純にcase変換だけを行うイメージです。 

そうですね．多分，そんな感じに実装すると思います．

>（あんまり使っている人いなそうですけど）ファイルを直接読み書きして何かやってる人には影響あるので十分なアナウンスとバージョンの検討は必要そうですね。

破壊的修正なので，修正する場合はmajor versionを上げます．

**Comment by masnagam** [comment]
- `clocks.json`: camelCase only
- `services.json`: mixed
  - .[][1].channel.extra_args
  - .[][1].channel.excluded_services
- `schedules.json`: camelCase only, but `$type` exists
- `recording/schedules.json`: mixed
  - [].program.start_at
  - [].program.event_group
- `*.record.json`: mixed
  - program.start_at
  - program.event_group
  - service.channel.extra_args
  - service.channel.excluded_services
- `*.timeshift.json`: mixed
  - service.channel.extra_args
  - service.channel.excluded_services
  - chunk_size
  - max_chunks
  - record.*.program.start_at
  - record.*.program.event_group

**Comment by masnagam** [comment]
stopped to investigate this issue anymore. because there is no simple way to solve this issue at this point. serde does not support filed name conversion based on serialized data format. this is correct direction to solve this kind of issues.
