### ISSUE TITLE
SERVICE_SPLIT=0 を無視する不具合

### ISSUE THREAD

**Issue by lkfejleene** [mirakc/mirakc#211]
user@TV:~$ uname -a 
Linux TV 5.4.106-1-pve #1 SMP PVE 5.4.106-1 (Fri, 19 Mar 2021 11:08:47 +0100) x86_64 x86_64 x86_64 GNU/Linux
ubuntu 20.10
DD MaxM4

以前衛生が受信できない件で大変お世話になりました。

今回は、Bondriver_mirakc.ini の SERVICE_SPLIT=0 指定を無視する不具合について報告させていただきたいと思います。

これは Bondriver.iniにSERVICE_SPLIT=0 を指定しているのに、TVTestでチャンネルスキャンを行うとBSCSだけがどうやっても1サービス1チャンネルになってしまうというものです。

今回検証土台として、mirakc 0.17.4使用しました。
　　TVTest0.10.0 + Bondriver_mirakc.dll 1.2  の場合、強制的に SERVICE_SPLIT=1 な挙動
　　TVTest0.10.0 + Bondriver_mirakurun.dll 1.5 でも強制的に SERVICE_SPLIT=1 な挙動
をしてしまいます。

さらに今回は他の御利用者様にご協力願って、チューナを  PX-W3U4 でも行っていただきましたが、やはり同様にSERVICE_SPLIT=1な挙動(1サービス1チャンネルモード)になってしまう様です。

お手数ですがmirakcのご確認を願えませんでしょうか？
宜しくお願いします。

**Comment by masnagam** [comment]
現時点では本件はmirakcの不具合ではないだろうと推測しています．そう考える根拠は次のとおりです．

そもそも，SERVICE_SPLITはBondriver_mirakcやBondriver_mirakurunの設定であり，その値をmirakcが直接参照することはありません．SERVICE_SPLITを変えたときの動作が変わるのはBondriver_xxxであり，mirakcではありません．

仮に，SERVICE_SPLITに関する不具合であったとしても，最初に動作確認すべきなのはBondriver_xxxです．Bondriver_xxxの修正のためにmirakcを修正する可能性はありますが，いきなりmirakcを修正することはありません．

１つの可能性として，config.ymlのチャンネル設定を確認すべきと考えます．BS/CSの設定で`services`を設定していたりしませんか？チャンネル設定で１サービス１チャンネルに設定していれば，常に`SERVICE_SPLIT=1`と同じ動作になると考えられます．以下のソースを確認すればそのことが理解できます．
https://github.com/epgdatacapbon/BonDriver_mirakc/blob/master/BonDriver_mirakc.cpp

以上の点を確認の上，やはり不具合だ考える場合は，まずはBondriver_xxxに不具合登録してください．

**Comment by masnagam** [comment]
#198 の[コメント](https://github.com/mirakc/mirakc/issues/198#issuecomment-825367160)を確認しましたが，やはりチャンネル設定で１サービス１チャンネルになっている可能性があると思われます．

```yml
name: 'ＢＳ朝日１'
type: 'BS'
channel: 'BS01_0'
services: [151]
```

`services`にSIDが１つだけ登録されているので，少なくとも`ＢＳ朝日１`はSID#151だけになります．他のチャンネルについても確認してみてください．

１サービス１チャンネルに設定していることが原因であれば，SERVICE_SPLITの不具合ではないため，Bondriver_xxxに不具合登録する必要はありません．

**Comment by lkfejleene** [comment]
ご確認、ありがとうございます。
正しくその通りの表記になっています。

確認させてください。
つまり正しくは、ここ(BSCS)のチャンネル設定は
```
name: 'ＢＳ朝日１'
type: 'BS'
channel: 'BS01_0'

name: 'どこかのCSチャンネル１'
type: 'CS'
channel: 'CS01'
```
と、servicesを外す表記すということでしょうか。

**Comment by masnagam** [comment]
はい，そうです．

`services`を指定すると，そのチャンネルには**指定したSIDのみ**含まれるようになります．`services`を削除すると，`channel`に含まれる全てのサービスがそのチャンネルに含まれるようになります．

具体例で説明します．

```yml
name: 'ＢＳ朝日１'
type: 'BS'
channel: 'BS01_0'
services: [151]
```

を

```yml
name: 'ＢＳ朝日１'
type: 'BS'
channel: 'BS01_0'
```

とすると，SID#151以外があれば含まれるようになります．もともとSIDが１つしかない`channel`では確認できないので，複数SIDが存在する`channel`で試して見てください．

`services`は特定SIDのみ含めるために利用するプロパティですが，特定SIDを除外するプロパティもあります．
https://github.com/mirakc/mirakc/blob/main/docs/config.md#channels

**Comment by lkfejleene** [comment]
なる程！
明快なご説明ありがとうございます。

私の方はよく理解できましたので、本件これにてcloseさせて頂いて宜しいでしょうか？

**Comment by masnagam** [comment]
解決したようなので，こちらで閉じます．

チャンネル設定を変更しても再現する場合は，Bondriver_xxxの不具合である可能性があるので，まずはそちらに不具合登録してください．
