### ISSUE TITLE
サービスが変更されない

### ISSUE THREAD

**Issue by lkfejleene** [mirakc/mirakc#346]
お世話になります

同一チャンネル複数サービスの局について、以下の様に定義しております。

  - name: 'ショップチャンネル'
    type: 'CS'
    channel: 'CS8'
    services: [55]

  - name: '東映チャンネル'
    type: 'CS'
    channel: 'CS8'
    services: [218]

  - name: 'Ｍｎｅｔ'
    type: 'CS'
    channel: 'CS8'
    services: [318]

  - name: '日テレＮＥＷＳ２４'
    type: 'CS'
    channel: 'CS8'
    services: [349]
    
このconfigで、日テレＮＥＷＳ２４(services: [349]) をTVTestで選局した時、
一番若いservice、この場合 ショップチャンネル(services: [55]) が表示されてしまいます。

TVTestのログにも

　　2022/01/15 6:26:59>******** TVTest ver.0.10.0-dev 0d0766e (Release x86) 起動 ********
　　2022/01/15 6:26:59>Work with LibISDB ver.0.0.0 519f918
　　2022/01/15 6:26:59>Compiled with MSVC 19.29.30133.0
　　2022/01/15 6:26:59>設定を読み込んでいます...
　　2022/01/15 6:26:59>プラグインを "D:\freesoft\TV\TVTest\Plugins" から読み込みます...
　　2022/01/15 6:26:59>TVCaptionMod2.tvtp を読み込みました。
　　2022/01/15 6:26:59>BonDriver_mirakc.dll を読み込みました。
　　2022/01/15 6:27:04>BonDriverにチャンネル変更を要求します。(チューニング空間 2[CS] / Ch 19[日テレＮＥＷＳ２４] / Sv -1)
　　2022/01/15 6:27:06>DirectShowの初期化を行います(MPEG-2 Video)...
　　2022/01/15 6:27:06>DirectShowの初期化を行いました。
　　2022/01/15 6:27:06>サービスを変更しました。(SID 55)

と、services: [55]が表示されます。

BSでも同様に、configが

  - name: 'ＢＳ朝日１'
    type: 'BS'
    channel: 'BS1_0'
    services: [151]

  - name: 'ＢＳ朝日２'
    type: 'BS'
    channel: 'BS1_0'
    services: [152]

  - name: 'ＢＳ朝日３'
    type: 'BS'
    channel: 'BS1_0'
    services: [153]

の時、ＢＳ朝日３(services: [153]) を選局すると、ＢＳ朝日１( services: [151]) が選局されます。

ご確認をお願い出来ますでしょうか？

環境：
　TVtest 0.10.0 0d0766e
　BonDriver_mirakc.dll 1.0 (SERVICE_SPLIT=0)

**Comment by masnagam** [comment]
最新の`mirakc/mirakc:alpine`において，「ＢＳ朝日」のケースのみKodiを使って確認しましたが再現しませんでした．

`ＢＳ朝日２`をKodiで選択した場合のログの抜粋:

```console
2022-01-15T09:58:40.511617+09:00  INFO mirakc_core::tuner: tuner#0.61: Activated with BS/BS1_0
...
2022-01-15T09:58:40.521567+09:00 DEBUG mirakc_core::command_util: tuner#0.61.1: Spawned 336: `mirakc-arib filter-service --sid=152`
...
```

`BS1_0`を開いて，`SID=152`をフィルターしています．

`ＢＳ朝日３`をKodiで選択した場合のログの抜粋:

```console
2022-01-15T09:51:18.990610+09:00  INFO mirakc_core::tuner: tuner#0.51: Activated with BS/BS1_0
...
2022-01-15T09:51:18.999044+09:00 DEBUG mirakc_core::command_util: tuner#0.51.1: Spawned 281: `mirakc-arib filter-service --sid=153`
...
```

`BS1_0`を開いて，`SID=153`をフィルターしています．

念の為，フィルター後のストリームの内容も確認しましたが，指定特定サービスのみとなっていました．

```console
$ curl -fsSL http://mirakc1:40772/api/channels/BS/BS1_0/services/153/stream | mirakc-arib scan-services
[{"nid":4,"tsid":16400,"sid":153,"name":"ＢＳ朝日３","type":1,"logoId":-1}]
```

ログレベルを変更し，ご自身の環境でログを確認してください．確認すべきポイントは．．

* 正しいチャンネルを開いているか (/api/tunersでも確認可能)
* `mirakc-arib filter-service`に正しいSIDが指定されているか

もし上記が間違っている場合，そもそもmirakcに対して間違ったリクエストを送っていることを意味するため，本チケットを閉じて，TVtestやBonDriver_mirakcをデバッグしてください．

不具合報告前に以下を参考にご自身で問題解析を行うようお願いします．
https://mirakc.github.io/dekiru-mirakc/troubleshooting.html

**Comment by lkfejleene** [comment]
ご確認ありがとうございます。

こちらでもAPIでの返答を確認しました。

お手数をおかけしました。
