### ISSUE TITLE
Improve the docker GitHub job

### ISSUE THREAD

**Issue by masnagam** [mirakc/mirakc#508]
Currently, it takes more than 1 hour and often fails due to some sort of time limits in GitHub Actions.

The build time of TSDuck is one of its root causes.

**Comment by masnagam** [comment]
cd46db2705043da8283c6c8ef5f91e47382d0ad8 improved the execution time.  See https://github.com/mirakc/mirakc/actions/runs/2868372678

**Comment by kounoike** [comment]
https://jondot.medium.com/shipping-rust-binaries-with-goreleaser-d5aa42a46be0 の記事にありますが、Rustでもあえてgoreleaserを使うことで、QEMUを使わずにビルドして高速にmulti platformのdocker imageが出来るようです

**Comment by masnagam** [comment]
@kounoike
情報ありがとうございます．

この修正前でもcross-compileしていたのでqemuは使用されていないはずです（今でも動作確認のためのテストの実行にはqemuを使用しています）．
mirakc/buildenvもlinux/amd64イメージしかないので，記憶違いはないだろうと思います．

mirakc/toolsイメージ含まれているバイナリーのビルド時間の大部分をtsduck-aribのビルドが消費していることまではわかっていますが，それ以上は未解析です（ビルドが遅い理由は不明）．
tsduck-aribはtsduckのforkなので（あと，可能ならtsduckをlibisdbに置き換えてしまおうとも考えていたので），あまり真面目に解析する気が起きず，上記のようなビルドを分離するという単純な方法を採用しました．

現状，青果物をdockerイメージにして，必要なものをすべて突っ込んであるので本プロジェクトでは利用しないと思いますが，debパッケージなどを配布するプロジェクトでは重宝しそうです．

**Comment by kounoike** [comment]
@masnagam ちゃんと調べず、 https://github.com/mirakc/mirakc/blob/44981614fe4a2d7d38581f5be189950e414b6c24/.github/workflows/docker.yml#L78-L79 でQEMU入れてるなー、くらいにしか見てませんでした。なるほど、動作確認のためだったのですね
7分×5プラットフォームが直列（github hosted runnerなら2コア並列かも？）に走ってるみたいですし、遅いのは仕方ないようですね

**Comment by masnagam** [comment]
確かに同時に実行するビルドの数は多いのですが，tsduckのビルドは大変遅いです．普通にpcでビルドしても遅いんです．

多分，インクルドパスに複数のディレクトリが指定してありヘッダーファイルの検索が遅いとか，テンプレートを過剰に利用しているなど，調べれば理由はわかるとは思うのですが，面倒なので調査していません．

libisdbは必要な機能が盛り込まれていても十分短い時間でビルドが完了します．最初にlibisdbを見つけていたらこんなにビルドに時間はかからなかっただろうと思います．

ビルドは遅いですが，tsduckにはxmlでts streamを定義できる機能があり，これがテストに使えて便利です．
libisdbなどは，あまりユニットテストがなく，テストを補助するような機能もないので，libisdbを使っていた場合にはテスト方法に困ったかもしれません．
