### ISSUE TITLE
dockerイメージ内ファイルの権限

### ISSUE THREAD

**Issue by uru2** [mirakc/mirakc#527]
dockerの ```-u``` オプションによるuid/gid指定で運用しようとして気づきましたが、linux/amd64の ```1.0.57, 1.0.57-alpine``` タグイメージ(現時点ではrelease最新イメージ)で ```/etc/mirakurun.openapi.json``` がroot以外読み取り不可になっているようです。

以下イメージビルド内でCOPYしているファイルのls結果です。
```
root@debian:~# docker run --rm -it --entrypoint= mirakc/mirakc:1.0.57 sh
#  ls -l /usr/local/bin/
total 10136
-rwxr-xr-x 1 root root 7849848 Aug 19 19:45 mirakc
-rwxr-xr-x 1 root root 2418040 Aug 17 07:27 mirakc-arib
-rwxr-xr-x 1 root root   42048 Aug 16 03:18 recdvb
-rwxr-xr-x 1 root root   58176 Aug 16 03:18 recpt1
# ls -l /etc/mirakc/strings.yml
-rw-r--r-- 1 root root 5568 Aug 19 19:28 /etc/mirakc/strings.yml
# ls -l /etc/mirakurun.openapi.json
-rw------- 1 root root 13970 Aug 19 19:48 /etc/mirakurun.openapi.json
#
root@debian:~# docker run --rm -it --entrypoint= mirakc/mirakc:1.0.57-alpine sh
/ # ls -l /usr/local/bin/
total 11632
-rwxr-xr-x    1 root     root       7956232 Aug 19 19:52 mirakc
-rwxr-xr-x    1 root     root       3751368 Aug 17 07:24 mirakc-arib
-rwxr-xr-x    1 root     root         94000 Aug 16 03:14 recdvb
-rwxr-xr-x    1 root     root        105968 Aug 16 03:14 recpt1
/ # ls -l /etc/mirakc/strings.yml
-rw-r--r--    1 root     root          5568 Aug 19 19:27 /etc/mirakc/strings.yml
/ # ls -l /etc/mirakurun.openapi.json
-rw-------    1 root     root         13970 Aug 19 19:55 /etc/mirakurun.openapi.json
/ #
```

おそらくはイメージビルド時にローカル側にあるファイル権限がそのまま反映されていると思うのですが、root以外読み取り不可となっているのは何か意図があってのことでしょうか？
なお1.0.57タグから派生させたDockerfileのビルドコマンドで ```chmod +r /etc/mirakurun.openapi.json``` とすれば ```-u uid:gid``` での指定でうまく動いているようです。

余談ですが、イメージ作成時にdvbv5-zap (Debian: dvb-tools, Alpine: v4l-utils-dvbv5) も含めていただけると個人的には助かります。

**Comment by masnagam** [comment]
特に何も考えずにコピーしていました．所有者以外が内容を読めたとしても何も問題はないので修正します．

`COPY`時に変更できるみたいです．週末にでも試してみます．無理なら素直に`chmod +r`します．
https://github.com/moby/moby/issues/34819

> 余談ですが、イメージ作成時にdvbv5-zap (Debian: dvb-tools, Alpine: v4l-utils-dvbv5) も含めていただけると個人的には助かります。

提案ありがとうございます．パッケージをインストールすればよいだけなので，追加しておきます．

**Comment by masnagam** [comment]
solved in b63bb07adf6a270f2f6ac2747bc767851b38f535 and 0a1b594f24e6416c6510501347a7afbf6763d58e

**Comment by masnagam** [comment]
applied to `release`

* 563a8310519107634bea122fc57b338d7631009c
* 4a73672bcc13f9580c08d254dee67283945042fa

**Comment by masnagam** [comment]
@uru2 イメージが生成されるのは来週末です．確認後，問題なければ閉じてください．

**Comment by uru2** [comment]
main, main-alpineイメージでは mirakurun.openapi.json が /etc/mirakc/ 配下に移動し全ユーザー参照できることを確認いたしました。

またreleaseイメージであるlatest, alpineについては来週改めて確認いたします。
その際に修正されていましたら本issueはcloseいたします。

**Comment by uru2** [comment]
latest, alpineタグで修正確認済みです。
