### ISSUE TITLE
タイムシフト録画機能でnum-chunksを変えて再起動すると、既存のdata-fileが消去される

### ISSUE THREAD

**Issue by vroad** [mirakc/mirakc#676]
タイムシフト録画機能でnum-chunksを変えて再起動すると、既存のdata-fileが消去されるようですが
これは仕様なのでしょうか？
m2tsのファイルはそのままだったものの、data-fileが消えたため、timeshiftfsで番組が最新の物を除き消えました。リングバッファの記録位置も最初からになったようです。
https://github.com/mirakc/mirakc/commit/103d84b4b25c6111b426e626c27029ac8a14bc7d からビルドしたものを使用しています。

たとえnum-chunksやchunk-sizeが変更不可能な仕様だとしても、録画開始しないより、既存のdata-fileをユーザーに尋ねずに消してしまう挙動の方がまずいかと思います。
既存data-fileのchunk_sizeと異なる場合はログにエラーを出し、録画開始しないようにしてほしいです。

最低でもこれらの設定値は変更不可能だという事をドキュメントに記載して欲しいです。自分で見た限りでは、できるmirakcにも、[docs/config.md](https://github.com/mirakc/mirakc/blob/main/docs/config.md#timeshiftrecorders)にもそのような記載は見当たりませんでした。

chunk-sizeを後で増やせるようにするのは難しいのでしょうか？
リングバッファの記録位置が最初に戻るのがもっと後の方になるだけで、可能かと思ったのですが、そうではないのでしょうか。

**Comment by masnagam** [comment]
ログが提供されていないので，どのようなことが起こっているのかわかりません．可能ならログの提供をお願いします．

１つの可能性として，epgキャッシュに保存されたサービス一覧が消えると，`ServicesUpdated`のハンドラー内でレコーダーがreactivateされるので，これで消えそうな気がしますが，実験してみないとわかりません．

また，仮に消えたとしても，問題発生時のログがないので，そちらで遭遇した問題と同じであるかどうか確認できません．実際に発生した問題を解決するためには，どうしても問題の詳細を知る必要があります．

> 既存data-fileのchunk_sizeと異なる場合はログにエラーを出し、録画開始しないようにしてほしいです。

エラーで即停止するだけならできそうです．ただ，そのためには以前の値をどこかに記録しておく必要があるので，データファイルの書式を変更する必要がある気がします．

> 最低でもこれらの設定値は変更不可能だという事をドキュメントに記載して欲しいです

確かに，設定値を変更した場合の動作について記述が必要ですね．追記することにします．

> chunk-sizeを後で増やせるようにするのは難しいのでしょうか？

即答はできません．考える時間が必要ですが，今はそれを取ることができません．

**Comment by masnagam** [comment]
本件に関する修正はv1にはマージしません．

**Comment by masnagam** [comment]
単純に考えれば，chunk-sizeやnum-chunksを変えても，すでに記録されたデータの位置は変わらないｓ，再起動後の書き込み位置も変わらない．単に変更後のデータ書き込み単位やファイル全体のサイズが変わるだけなので，以前のデータを保持し続けることは可能と思われる．

**Comment by masnagam** [comment]
多分ここで空になる．
https://github.com/mirakc/mirakc/blob/main/mirakc-core/src/timeshift.rs#L480

どうやら各サイズは記録されていて，値が一致したときのみよみこむようになっている．

**Comment by masnagam** [comment]
値不一致時に即停止したとして，ユーザーができることは．．

1. 元の値に戻して再起動
  * データは消えないが，本来は値を変えたかったので，やりたかったことはできていない
2. データファイルを消して再起動
  * データファイルを消さないと起動できないので，起動するためには消すしかない

のどちらかで，これらを実行する前に消えてしまうデータをどこかに退避させることになる．

通常，tsファイルは非常に巨大であり，これを退避するというのは現実的ではない．やはり，可能な限りデータを保持することが望ましい．

chunk-sizeやnum-chunksを減らした場合，tsファイルのサイズが小さくなる．単純にtsファイルのサイズを小さくすると，元ファイルの後半部分が消える．

* `TimeshiftRecord`は`start`と`end`を保持しているため，消えたことを検出できる
* 書き込み再開位置が削除分に含まれているなら，最初に戻れば良い

`points: Vec<TimeshiftPoint>`の扱いが問題．`TimeshiftPoint`は`timestamp`を保持しており，これをchunk-size変更時に適切に書き換える必要がある．常にtsファイルの最初から書き込みを行うのであれば`points`を空にしてしまうだけで良いが，可能な限り続きから書き込むなら適切に更新する必要がある（tsファイルへの書き込みはチャンク単位なので，完全に同じ場所からというのは保証できない）．

**Comment by masnagam** [comment]
続きは録画機能実装後に．．

**Comment by vroad** [comment]
返信ありがとうございます。

> 本件に関する修正はv1にはマージしません．

運用方針がどのようなものか分かりませんが、バグ修正も含め全ての修正はv2で行うってことでしょうか？
値を変更できるようにするなど、本格的な対応は後回しにするとしても、
num-chunksの値が異なる場合にエラーですぐに停止する等の対応も行いませんか？

原因は https://github.com/mirakc/mirakc/blob/main/mirakc-core/src/timeshift.rs#L480 にあるということで、値を変えさえしなければ今後は起きないと言う事は分かったのは良いのですが、
エラーで停止する等の対応をしないと他にも同じ問題に遭遇する方が出てくるかと思います。

**Comment by vroad** [comment]
残ったm2tsをそのまま再生しても、再起動後に録画された部分が終わると止まってしまい
再生できませんでしたが、
ddコマンドで消えてない部分のm2tsの内容を取り出せば
番組タイトルなどは分からなくなるものの、再生する事は出来ました。
まだファイルサイズが小さければこの問題が起きても映像だけは復元できそうです。
（ファイルサイズが大きく作業領域が足りない場合は、値を変えて何度もddを繰り返すとかで出来るかもしれません。）

```
dd skip=8 count=1587 if=./nhk.timeshift.m2ts of=nhk-cut.m2ts bs=163840000
```

録画先がbtrfsならファイルの一部をreflinkでコピーができるそうなので
それを使うかですね。
ただどのツールでそれが出来るか分からず。

**Comment by masnagam** [comment]
> バグ修正も含め全ての修正はv2で行うってことでしょうか？

極力記録を削除しないような修正はv2でのみ行います．
timeshift.rsはそれほど差分がないので，もしかするとパッチは当たるかもしれませんが，v2をリリースするとv1はメンテ対象外にする予定なので，v1には適用しないつもりです．

今の所，一人で開発を行っているので，運用方針などは何もありません．複数人で開発するなら必要なのでしょうが．

> num-chunksの値が異なる場合にエラーですぐに停止する等の対応も行いませんか？

行ってもよいと思っていますが，「v2をリリースすると．．．」で書いたような事情があるため，仮にv1に停止対応を入れたとして，その対応に問題・不満があったとしても，メンテ対象外なので私は対応しなくなります．そのため，どうしようかと考えています．v2リリースは数ヶ月先だろうと思うので，やったほうが良さそうですが．

もちろん，PRは受け付けています．

> 今後は起きないと言う事は分かったのは良いのですが

他にも消えてしまうケースがあるかどうかは少し考えないと行けないと思っています．ドキュメントに追記するなら確認が必要ですね．

**Comment by masnagam** [comment]
> 録画された部分が終わると止まってしまい

ts-fileはリングバッファーになっているので，データを取り出すには少し工夫が必要ですね．

> この問題が起きても映像だけは復元できそうです

単にサービスのTSストリームを書き込んだだけなので，TS解析ツールを駆使すれば，data-fileの内容をある程度は復元できるだろうと思います．ちょっと実験してみます．

**Comment by masnagam** [comment]
こんな感じでなんとかなるかも．．

```sh
# sid抽出
SID=$(cat bs.timeshift.m2ts | mirakc-arib scan-services | jq '.[].sid')

cat bs.timeshift.mt2t | mirakc-arib record-service --sid=$SID --file=tmp.m2ts \
  --chunk-size=<元のサイズ> --num-chunks=<元のチャンク数>
```

JSONが出力されますが，各番組の情報と共に開始位置・終了位置も出力されます．

`MIRAKC_ARIB_LOG=debug mirakc-arib record-service ...`でログを出力させると，warningが出ているのが確認できますが，データはそれなりに取り出せているように見えます．

サイズは大きくなってしまいますが，元のts-fileを２回catすれば１つ目の最後と２つ目の最初で連結されるので，リングバッファーの問題も回避できます（ただし，サイズが２倍になってしまいますが）．つなぎ目の部分でTSが不連続となるため，どうしても問題が発生しますが，上記のような簡単な方法でもある程度は情報を復元できそうです．

**Comment by masnagam** [comment]
`--file`に/dev/nullを指定することも可能ですが，この場合は１チャンク分しか出力されません（`fsync`で失敗するためです）．`cat`している部分を１チャンクづつ入力していけば（更にファイルを２周する），ストレージを消費せずにデータの復元が可能かもしれません．

**Comment by masnagam** [comment]
基本的に`mirakc-arib record-service`がやっていることは

* stdinから入ってきたTSストリームを解析して，内部状態を更新後，そのままファイルに（チャンク単位で）出力
* イベントをstdoutにJSONで出力

しているだけなので，*.timeshift.m2tsファイルを入力すれば，（ほぼ）録画時の状況を再現できます．

**Comment by masnagam** [comment]
以下の手順で最小限の欠落でデータを復旧できると思います．

1. timeshift.m2tsに含まれるチャンクを時系列順に並べ直す（rotateする）
    * タイムシフト録画を何度か停止している場合，不連続チャンクが複数作成されるが，リング境界以外では時系列順にならいんでいる
    * リング境界では過去に戻るため，リング境界の検出は簡単
        * 各チャンクを読み込み，TOTを探す
        * TOTは５秒間隔で出現するので，チャンクすべてを読み込む必要はない
        * `cat timeshift.m2ts | mirakc-arib sync-clocks | jq '.[].clock.time'`でUNIX time (milli-seconds)が取得できる
2. 新しいチャンクサイズ，新しいチャンク数でnew.timeshift.m2tsを作成
    * もちろん古い値でも可
    * new.timeshift.m2tsのサイズが小さくなっても良い
        * この場合，古いデータから順に消されていく
4. `cat timeshift.m2ts | mirakc-arib record-service --sid=<sid> --file=new.timeshift.m2ts --chunk-size=<新しいサイズ> --num-chunks=<新しいチャンク数>`を実行
    * 出力されるJSONからnew.timeshift.jsonを再構築すれば，新しい値用のファイルが完成

現在，出力JSONからnew.timeshift.jsonを構築するツールはmirakc以外ありません．この部分をツール化（mirakc-aribのコマンド化）すれば，簡単にサイズ変更できそうな気がします．

**Comment by masnagam** [comment]
v1とv2ではtimeshift.jsonの書式が違うので（ https://twitter.com/masnagam/status/1589962200701374465 ），v2向けのツールはv1には使えない．v2移行時は使える．

**Comment by vroad** [comment]
ありがとうございます。

> 出力されるJSONからnew.timeshift.jsonを再構築すれば

とありますが、現状はコマンド無いんですよね。mirakc-aribで番組がファイル内のどこで始まるかは分かるようになったので、ddコマンドでtsから番組を切り取って復元しました。
私の場合、データが消える前の時点ではリングバッファはまだ一周していないかったため、時系列通りでない事による問題は起きないかと思います。

ddで切り取る時、mirakcを再起動して録画が途切れた部分を含めてしまうと、プレーヤーの再生が終了したりとか、データとして正しくないTSが出来てしまうので
その部分は2回ddを行って2つのファイルにしました。

**Comment by masnagam** [comment]
情報ありがとうございます．参考になります．

> 現状はコマンド無いんですよね

ないですね．先のコメントに書きましたが，mirakc以外でそのような処理をしているものはないです．そのため，この部分をツール化することを考えています．壊れることはたまにあるので，timeshift.m2tsファイルのみから復旧する方法はあってよいだろうと思っています．

> mirakcを再起動して録画が途切れた部分を含めてしまうと、プレーヤーの再生が終了したりとか、データとして正しくないTSが出来てしまうので

なるほど．resyncしないプレーヤーがあるんですね．[resync自体は難しくない](https://github.com/mirakc/mirakc-arib/blob/main/src/packet_source.hh#L124)ので実装しているだろうと思っていたのですが．

流石に不連続TSパケットはサポートしていると思うので（パケットドロップがあると再生できないとか普通ないですし），一度`mirakc-arib filter-service`に通して，resyncしてやれば連結できるのではないかと考えます．もちろん，映像は不連続になりますが．

**Comment by vroad** [comment]
> なるほど．resyncしないプレーヤーがあるんですね．[resync自体は難しくない](https://github.com/mirakc/mirakc-arib/blob/main/src/packet_source.hh#L124)ので実装しているだろうと思っていたのですが．

試したプレーヤーはmpvとVLCです。MPEG2 TSの仕組みは詳しくないですが、
録画が途切れた付近にシークしたら、全然違う時間が表示されるなどプレイヤーの動作が変になるので
多少ドロップが生じた場合とは何か違うのかと思います。

どうしても途切れが生じてる付近の録画も見たいってなったら `mirakc-arib filter-service` も試そうかと思います。

**Comment by masnagam** [comment]
情報ありがとうございます．ツールを作成したときに動作確認が必要なので参考になります．

**Comment by masnagam** [comment]
サイズ変更などの理由でdata-fileの読み込みに失敗した場合に，プロセスを即停止するように変更 bd15d53511fab2e7d700b616fde24a86f2017cc3

**Comment by masnagam** [comment]
回復ツールは後で作る

**Comment by vroad** [comment]
@masnagam 
まだファイルが消える状況があるかもしれません。
mirakc-timeshift-fsの変更のテストのため、3532010fc05011e356398c31caf56d7b7dd49e3a で使っていましたが、
うっかりbtrfsのスナップショットをそのままにしていたらHDDの空きが不足し、data-fileが空になっていました。

`ERROR mirakc_core::timeshift: nhk: Failed to save data into /mnt/hdd0/mirakc/timeshift/nhk.timeshift.json: std::io error: No space left on device (os error 28)`

**Comment by vroad** [comment]
ストレージの空きをチェックするのではなく
新しいファイルに変えてからリネームすれば良いのでは？

今の実装では、ストレージの不足時だけでなく、書き込み中にPCの電源が切れたり何らかの理由でシステムがクラッシュした場合もdata-fileが空になったり、途中までしか書かれていない状態になる危険があります。少なくともこれは回避すべきです。

更新時は、ファイルに追記してるわけではなくファイルの中身を消して最初から書き直ししてるんですよね。
Atomというエディタにも昔、ファイルを保存時にディスク空き容量がないとデータが消えるという同様の問題がありましたが

https://github.com/atom/atom/issues/3158#issuecomment-119353730
https://stackoverflow.com/questions/1812115/how-to-safely-write-to-a-file

1. "nhk.timeshift.json.new" という名前でファイルを作成する
2. "nhk.timeshift.json" にリネームする。（既にファイルがあっても上書きできます）

のようにする事で回避できます。この実装なら、mirakcがクラッシュすると.newが残る事はあるかと思いますが、OSのファイルのメタデータ更新はアトミックに行われるので、データが空になったり途中までしか書かれていない状態になることはありません。
ただdata-fileはmirakcを再起動するまで
古い番組の部分が整合性取れていない状態になるかとは思います。

mirakcがWindows対応か分からないですが、
MacやLinuxだけではなく
Windowsでも同様の実装が可能と思われます。

https://stackoverflow.com/questions/167414/is-an-atomic-file-rename-with-overwrite-possible-on-windows/2368286#2368286

**Comment by vroad** [comment]
> 「できるmirakc」ではts-fileのみfallocateしていますが，data-fileについても同様の前処理を行うのが良いのかもしれません．

jsonの記録が止まるのは解決するかもしれませんが、同じファイルを書き込みモードで開いて
直接書き換えるという実装を使い続ける限り
jsonの書き込み中にクラッシュするとデータが無くなるのは解決しないかと思います。

.newで終わるファイル名で新しい版のファイルを作ってリネームでjsonを上書きってテクニックとも合わないかと思います。
リネームにした時にfallocateしていても消えちゃうので。

前述の「新規作成＆リネーム」の手法なら大きな手間を掛けず実装可能かと思いますがどうでしょう。

**Comment by masnagam** [comment]
> 前述の「新規作成＆リネーム」の手法なら大きな手間を掛けず実装可能かと思いますがどうでしょう。

そうかもしれませんが，すべて自分でやろうという考えはありません．大変なので，できるだけ実装したくないのです．

ただ，どうしても「必要な」機能というものはありますし，自分がほしいと思っている機能もあります．それさえ実装できれば私は満足ですし，それ以上のことをやりたいとは思いません．

必要だと思う機能は，そう思う人が実装・保守するのが一番なのです．

> 新しいファイルに変えてからリネームすれば良いのでは？

これは私も考えたのですが，この場合，data-fileをもう１つ作ることになるので，それだけのストレージが確保されていないと書き込みができません．ストレージ状況を確認する実装をした場合と同じ同期問題は残ります（これはvroadさんも書かれていることですが）．

> 途中までしか書かれていない状態になる危険があります。

この場合，jsonのparseに失敗するので，v2では起動しなくなります． bd15d53511fab2e7d700b616fde24a86f2017cc3

その後，回復ツールでdata-fileを復元するという流れを考えています．

ただ，空ファイルの扱いが問題ですね．．空ファイルだけでは，これが`touch <data-file>`でとりあえず作っただけのファイルなのか，openでサイズ0になったのか判別できないです．少し検討が必要ですね．結果としてrename案を実装する可能性はありますね．

> 古い番組の部分が整合性取れていない状態になるかとは思います。

どのような保存方法であってもこの状態を確実に回避することはできないので，data-fileを回復するツールを作らなくてよいということにはなりません．なので，私はこれだけで済ませたいと考えています．ただ，先にも書きましたがPRを拒否するという意味ではないので，誰かが実装するのを阻害することはしません．

> mirakcがWindows対応か分からないですが

残念ながら対応していません．
mirakc自体は動くかもしれませんが，mirakc-aribはwindowsでは動作しないので，これに変わるものが必要です．

----
もし直接話がしたいということでしたら（issueを使ったチャットだとやり取りに時間がかかるので），メールでgoogle meetなどのurlを送ってくだされば，直接話すことも可能です．

**Comment by vroad** [comment]
> 新しいファイルに変えてからリネームすれば良いのでは？

これ「新しいファイルに"書いてから"」と書いたつもりだったのですが「変えてから」になってました。意味は理解できたかと思いますが一応・・・

> 必要だと思う機能は，そう思う人が実装・保守するのが一番なのです．

分かりました、Rustは全くやったことないですが、リネーム後に保存する変更のみなら私でも作れるかもしれないので、
もしmasnagamさんがやらないのであれば後日実装を試みようかと思います。（空ファイルの取り扱いを検討後、結果的に実装するかもとも書かれていますが）

ストレージ不足は十分注意すれば回避出来るかと思いますが、クラッシュ(or電源断)は100%回避できないかと思うので、その時data-fileが失われるのは回避したいです。
この場合は再起動で録画が再開可能と思います。
リングバッファの位置が少し戻ってしまい、クラッシュ直前の録画が少し失われても、手動での操作なしで再起動後に自動で録画を再開されるとありがたいです。

不注意によるストレージ不足の場合は自動では対応できないので、この場合に回復ツールを使うという点に対しては異論ないです。

meetでの直接会話は・・・すみませんが今は遠慮しておきます。

**Comment by masnagam** [comment]
> クラッシュ(or電源断)は100%回避できないかと思うので、その時data-fileが失われるのは回避したいです。

その意見に同意します．

> この場合は再起動で録画が再開可能と思います

linux kernelの詳細を知らないと確実なことは言えませんが，mv中にクラッシュ(or電源断)が発生すると，この方法でもファイルが壊れる可能性があるのではないでしょうか．

mvはinode情報の書き換えだけですが，これも最終的にはブロックデバイスに書き込まないと反映されないはずなので，確実ということではない気がします．もちろんmvで壊れる事象が発生する頻度は格段に低いとは思いますが．

このあたりは，一般的なデータベースがlinux上でどのように保存処理を行っているのか参考にするのが良さそうな気がしますね．残念ながら私はデータベースを実装したことがないので，詳細はわかりません．

> 手動での操作なしで再起動後に自動で録画を再開されるとありがたいです。

同意しますが，回復処理にどのくらい時間がかかるのかもまだわかりませんし，できるともできないとも言えないですね．

実装の順番としては

1. 手動で回復するツールを作る
2. 可能なら，このツールをmirakc起動時に実行して自動回復

手動回復のツールは必要なので，まずはこれを作ってみて，その後どうするか考えるというのがよいと思っています．

**Comment by vroad** [comment]
> linux kernelの詳細を知らないと確実なことは言えませんが，mv中にクラッシュ(or電源断)が発生すると，この方法でもファイルが壊れる可能性があるのではないでしょうか．

壊れたとはどのような状態でしょう？
一般的なジャーナリングファイルシステムであれば、mvによるメタデータの変化がデバイスに書き込まれる前にクラッシュ(or電源断)しても再起動後に正常に復帰し、古いファイルが残るはずです。exFATとかのジャーナリング無いファイルシステムはどうなるか分かりませんが。

ただ、古いバージョンのLinuxカーネルのext4の実装では、Delayed Allocationにより
新規ファイルへの書き込みよりリネームが先に行われてしまい、この「新規作成＆リネーム」の手法を使っていても
サイズが0のファイルが出来ることがあったようです。

2009年にリリースされたLinux 2.6.30以降は、少なくともデフォルト設定でext4を使えば、リネームが絡む操作の場合はリネームが後になるように修正されたのでこれも問題ないかと思います。
他ファイルシステムは分かりませんが、この手法を使っているアプリケーションは多いと思うので
ext4同様に消えないように配慮はされているのではないでしょうか。

https://en.wikipedia.org/wiki/Ext4#Delayed_allocation_and_potential_data_loss

> 理解できますが，回復処理にどのくらい時間がかかるのかもまだわかりませんし，できるともできないとも言えないですね．

「新規作成＆リネーム」の手法だけでも導入すれば、少なくとも古いバージョンのファイルは残ります。
現状も起動時の回復処理はないかと思いますが、最悪でも最後に録画したチャンクの部分が上書きされて失われるだけかと思うので
クラッシュの場合の対応としては再起動後の回復処理はなしでも良いのではないでしょうか。

もちろん、自動で回復処理が走って、最後のチャンク部分も出来る限り回復してくれるならそれがベストではありますが。

不注意によるストレージ不足の場合は、気づくまでの時間によっては録画が続いているのにdata-fileが更新されない状態が長時間そのままにされる可能性もあるので、ストレージ不足も救済可能にするならもっと必要性が増すと思います。

**Comment by masnagam** [comment]
> 壊れたとはどのような状態でしょう？

inode情報の保存に失敗したような状態ですね．ジャーナリングの詳細を理解していませんが，記述していただいたような内容であれば，mv中のクラッシュ(or電源断)はext4などでは救済されているようですね．

> クラッシュの場合の対応としては再起動後の回復処理はなしでも良いのではないでしょうか。

data-file保存中のクラッシュの場合はそうですね．

chunk-sizeを変更した場合など，古いdata-fileがそのままでは読み込めない場合あるのですが，これを救済しないとするなら，renameでの保存のみやれば良くなるので，こっちのほうが楽ですね．

**Comment by masnagam** [comment]
作業ブランチ https://github.com/mirakc/mirakc/tree/fix-676

**Comment by masnagam** [comment]
誤ってmirakcを多重起動するとts-fileが壊れる（壊れる可能性のあるファイルは他にも存在する）．これは修正前でも同じ．本件に対する修正でdata-fileに対するlockファイルを削除したが，mirakcの多重起動防止用に別のlockファイルを導入したほうが良いかもしれない．

`mirakc-arib record-service`を直接実行することも可能なので，タイムシフト録画用のlockファイルは`mirakc-arib record-service`でチェックしたほうが良いかもしれない．検討も含め後で別途修正する．

**Comment by vroad** [comment]
renameでの保存は作業ブランチで実装したのですね、ありがとうございます。

このブランチのをビルドして使おうとしましたが、
チャンクサイズが 875ec95b0e95ff235d6e4a85f505d367f71fc33a から154MBの倍数から受け付けなくなっていて、metadata JSON files (data-file？)の正しい移行方法も分からないので
このコミットはrevertした物をビルドしました。
1d63adb0e7f23d7372f80a288d7f95b5d000c8e4 からチャンクサイズの強制を行うコミットを取り消したmirakcをしばらく使用しましたが、
試した限りでは問題ないかと思います。

これがmainに取り込まれたらcloseしようと思います。

**Comment by masnagam** [comment]
> 試した限りでは問題ないかと思います。

確認ありがとうございます．

> チャンクサイズが https://github.com/mirakc/mirakc/commit/875ec95b0e95ff235d6e4a85f505d367f71fc33a から154MBの倍数から受け付けなくなっていて

厳しすぎたかもしれません．

まだ実験していないので回復処理でどれくらいデータの欠損が発生するのか不明ですが，量が少ないようなら以前の拘束条件（8192の倍数）に戻すことにします．

> これがmainに取り込まれたらcloseしようと思います

可能ならテストを追加したいので，それが終わったらmainにマージします．
