### ISSUE TITLE
"No packet came from the tuner within the time limit, stop"のエラーが放送休止時にログに記録される

### ISSUE THREAD

**Issue by vroad** [mirakc/mirakc#693]
mirakcのバージョン: 1d63adb0e7f23d7372f80a288d7f95b5d000c8e4 からチャンクサイズのチェックを取り除いたもの

mirakc-timeshift-fsから見られるファイルのうち
13日頃からの物以降が全てmpvやVLCで正常に再生できないm2tsになっていました。
再起動すると正常に録画されるようになりました。

`ERROR mirakc_core::broadcaster: tuner#0.0: No packet came from the tuner within the time limit, stop` の起きた時刻あたりからm2tsが正常に記録されていないようですが、今回はなぜ起きたのか分からないです。

`WARN mirakc_core::broadcaster: tuner#1.1: No space for tuner#1.1.1, drop the chunk` もログに記録されていますが、これがログに記録されてもすぐ録画が途切れる訳ではないようです。

mirakcのログ全部をgistに上げました。
https://gist.github.com/vroad/23d51a93d547cd7a86f87a4215de2a20

問題が起きて正常に録画できていない場合に知る方法ってあるでしょうか？
録画できなくなった時、必ずこのエラーがログに記録されるなら
このエラーがログに記録されたら通知するように
mirakcのログを別プログラムで見るのでも良いかと思いますが、
もっと確実な監視方法はありますか？

追記：当初、「"No packet came from the tuner within the time limit, stop"のエラーで全録が録画されなくなる」というタイトルにしていましたが、録画が再生できないのは実際には別の問題だったためタイトルを変更しました。
タイトルのエラーは少なくとも一部の地域で必ず同じ時間帯に記録されるようです。録画は停止しますが、次にscan-servicesが動いた時に再開されます。

**Comment by masnagam** [comment]
まず，安定的な運用を目的にしているのであれば，`main`ではなく`release`を使ってください．`main`は開発中のコードなので色々問題があります．

> ERROR mirakc_core::broadcaster: tuner#0.0: No packet came from the tuner within the time limit, stop

チューナーからのパケット供給が停止したようです．`[tuners[].time-limit](https://github.com/mirakc/mirakc/blob/main/docs/config.md)`の既定値は30sです．

ログを調べると，`tuner#0.0`は`channel=GR/13`を開いているようです．

```
Jan 12 13:56:55 mirakc-start[12015]: 2023-01-12T13:56:55.968316+09:00  INFO mirakc_core::tuner: Activated session.id=tuner#0.0 channel=GR/13
```

チューナーコマンドの詳細はログに記録されていないのでconfig.ymlを見ないとわかりませんが，何らかの理由で

* チューナーコマンドが終了した
* チューナーコマンドは終了してはいないが，30秒間パケットの供給が停止した

ようです．チューナーコマンドの動作を確認してください．

> もっと確実な監視方法はありますか？

v2では`config.events`が追加されましたが，タイムシフト関係は追加していません．どうするか検討中です．

このような状況なので現状ログしか使えませんが，`ERROR mirakc_core::timeshift: nhke: Stopped recording due to some accident, reactivation count reached the maximum number`のほうが良いかもしれません．これが出ると，タイムシフト録画の再起動をしなくなります．

以下，ロクの説明を記述しておきます．v1とv2ではログ形式が違うかもしれません．

```
INFO mirakc_core::timeshift: nhke: Stopped recording
```

タイムシフト録画している`mirakc-arib record-service`が録画を停止したら必ずこのログが出力されます．

```
WARN mirakc_core::timeshift: nhke: Recording pipeline broken, reactivate
```

`ERROR mirakc_core::broadcaster: tuner#0.0: No packet came from...`が発生すると，パイプラインが壊れます．

```
INFO mirakc_core::timeshift: nhke: Deactivated
```

理由が何であれ，タイムシフト録画が停止したらこのメッセージが出力されます．

```
WARN mirakc_core::timeshift: nhke: Stopped recording due to some accident, activate it again
```

タイムシフト録画の再起動を試みています．無限に繰り返すわけではないので，最後は

```
ERROR mirakc_core::timeshift: nhke: Stopped recording due to some accident, reactivation count reached the maximum number
```

で再起動しなくなります．

`WARN mirakc_core::broadcaster: tuner#1.1: No space for tuner#1.1.1, drop the chunk` は関連するissueが存在します．

* #236

ディスクの書き込みが追いついていないなど，チューナーから供給されるパケットを処理しきれず，バッファーが溢れているのかもしれません．

**Comment by vroad** [comment]
> まず，安定的な運用を目的にしているのであれば，`main`ではなく`release`を使ってください．`main`は開発中のコードなので色々問題があります．

v1を使うと最近のissueで修正した問題も再発しますよね？まだbackportされてないかと思います。
data-fileもv2では互換性が無いという話なので
m2tsと一緒に退避して新規作成するか、何らかの変換処理が必要ですよね。

v1にすぐダウングレードするのはちょっと難しそうなので、録画用PCの負荷などの情報がわかるようにモニタリングを設定しようかと思います。

* [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics)
* [Prometheus Node exporter](https://github.com/prometheus/node_exporter)
* [Process Exporter](https://github.com/ncabatoff/process-exporter)
* [Grafana](https://github.com/grafana/grafana)

電力消費を少しでも減らそうと ` x86_energy_perf_policy` でCPUのTurbo Boostを止めたのが問題を誘発したのかと思いますが、特に問題なく録画が続いてることもあって本当にそれが原因か分からないです。
Turbo Boostは再度有効にして様子を見てみます。

config.ymlは以下を使用しました。
https://gist.github.com/vroad/b88b6dee4e720d7282350ab85ca65516

> * チューナーコマンドが終了した
> * チューナーコマンドは終了してはいないが，30秒間パケットの供給が停止した

このような状況の場合mirakcが出来る事あるのでしょうか？

**Comment by vroad** [comment]
ログを読んでアラートを発することをしなくても、APIで現在正常に録画中のチャンネルの情報が取れれば[json_exporter](https://github.com/prometheus-community/json_exporter)で監視出来るかもしれません。
録画できなくなった時、`/api/timeshift` で`recording`が`false`になるなら
それで監視できそうです。このフィールドは録画失敗時にfalseになるでしょうか？


https://stackoverflow.com/questions/49917316/jsonpath-get-length-of-array-after-filter

チューナーコマンドが正常に動作せず、最大リトライ数を超過した場合はmirakcを再起動できるようにするという手はあるかもしれませんが、
必ずしも再起動で直るとも限らないかと思いますし、1チャンネル失敗した時点で再起動すると他に正常に録画できているチャンネルがあっても止まってしまうのが良くないですかね。

**Comment by masnagam** [comment]
> m2tsと一緒に退避して新規作成するか、何らかの変換処理が必要ですよね。

そうですね．必要です．

v2は十分に動作確認できてないので，他の問題に出くわすかもしれませんが，容赦してください．

> このような状況の場合mirakcが出来る事あるのでしょうか？

私の推測が当たっているなら，mirakc側で出来ることは何もありません．チューナーコマンドより先（`recpt1`及びデバイスドライバー）をデバッグするしかないです．

https://mirakc.github.io/dekiru-mirakc/latest/troubleshooting.html にパイプラインの子プロセスのログを出力する方法が記載されています．これを使えば`recpt1`のログを記録可能ですが，デバイスドライバーはシステムのログを確認する必要があります．

**Comment by masnagam** [comment]
> このフィールドは録画失敗時にfalseになるでしょうか？

レコーダーは自動で再起動を試みるので，その間はタイミングによってtrue/falseの可能性があります．

最大リトライを超過したらfalseのままです．

> 必ずしも再起動で直るとも限らないかと思いますし

そうですね．．ログを見る限りnhkeとkbs以外は問題なく動いているようですし．

リトライではチューナーを開き直すのですが，それでも失敗しているようなので，mirakcを再起動しても失敗を繰り返す可能性は高いように感じます．

**Comment by masnagam** [comment]
config.ymlを見たところ，epg関係のジョブが有効になっているみたいですね．

タイムシフト録画にしか使っていない場合，以下の２つのジョブは無効化できます．

```yaml
jobs:
  sync-clocks:
    disabled: true
  update-schedules:
    disabled: true
```

どちらも既定値では日に２回しか実行されないので，動いていたとしても大した影響はないとは思いますが．
ちなみに，無効化すると`/api/programs`や`/api/programs/{id}/stream`が機能しなくなります．

できるmirakcにも記載してなかったようなので，後で最新版に追記しておきます．

**Comment by vroad** [comment]
ありがとうございます。
`recpt1`のログを取るには最低でも以下の設定が必要そうですね。

```nix
{
  environment = {
    TZ = "Asia/Tokyo";
    MIRAKC_DEBUG_CHILD_PROCESS = "1";
    RUST_LOG = "info,mirakc=debug";
  };
}
```


EPG関連は現在活用してないので、無効化してみます。

> そうですね．．ログを見る限りnhkeとkbs以外は問題なく動いているようですし．

ログを見る限りはそうですが、他のチャンネルも録画されていなかったです。

設定変更のためにmirakcを再起動して試していましたが、
`b25_decode failed (code=-9). fall back to encrypted recording.`

**Comment by vroad** [comment]
途中で書いてしまいましたが、recpt1が`b25_decode failed (code=-9). fall back to encrypted recording.`とログに出力する場合が稀にあり、recpt1かカードリーダー周りに問題あるかもしれないです。

recpt1は最初はstz2012氏の版を使ってましたが、
mpvでリアルタイム視聴時、ワンセグ画質が選択される場合があり
recpt1は http://hg.honeyplanet.jp/pt1/ の物を試していたのですが、
試してみて同様の問題が起きたにも関わらず戻していませんでした。

関係あるか分かりませんが、こちらもstz2012版に戻そうかと思います。

**Comment by masnagam** [comment]
> 最低でも以下の設定が必要そうですね

その設定で各コマンドのstderr出力内容が表示されるようになると思います．かなりたくさんログが出るのでgrepなどを必要に応じて使用してください．

もう少し効率よくdebugログを集められるようなログフィルターを見つけられたら，できるmirakcに記載することにします．

現在，ログ出力を調整中なのでリビジョンによってうまくフィルターできないかもしれませんが，例えば以下のような感じです．

```
export RUST_LOG='info,[pipeline]=debug'  # パイプライン系のみdebugレベルに
export RUST_LOG='info,[pipeline{label="timeshift"}=debug'  # timeshiftパイプラインのみ
```

`RUST_LOG = "info,mirakc=debug"`なら確実にdebugレベルのログが出ます．

**Comment by vroad** [comment]
ありがとうございます、試してみます。

Prometheus(or VictoriaMetrics)で
json_exporterを使って`/api/timeshift`に含まれる値を記録するのは以下のgistで書いたような設定でできました。

https://gist.github.com/vroad/f5bda39d0183a76832928387744acd08

durationも見れるようにしました。
`rate(mirakc_timeshift_duration[15m])` のようなPromQLで1秒間に増えたdurationの量を見れば、
異常が起きた場合値の上昇が止まるはずなので、リトライ中でも異常が起きているか分かりそうです。

しかしまだ原因が分かりませんね。@masnagamさんの言ったように、mirakcの外に原因があるかもしれませんし、具体的な情報が得られるまでクローズしますか？

他に問題発生時の詳細な情報を集める手段はあるでしょうか。
ドロップ数もmirakcのAPI、Victoria Metrics、json exporter、Grafanaの組み合わせで見ることが出来ると嬉しいですが、現在は無いですよね？ログには残るようですが。
recpt1が`fall back to encrypted recording`の状態になっているかもログで確認が必要ですよね。

問題が起きてる場面に遭遇できたら、その時のメモリダンプを保存する手もありそうですが、調べないと
すぐにはやり方わからないですね・・

**Comment by masnagam** [comment]
> 具体的な情報が得られるまでクローズしますか？

このままオープンのままで良いと思います．

> 他に問題発生時の詳細な情報を集める手段はあるでしょうか。

基本的にはログ以外にはないですね．

> 現在は無いですよね？

issuesにも残っていますが，統計情報の収集は未実装です．

json形式でログを出力できるようになっているので，これを別プログラムにpipeして解析し，Jaegerなどに転送するという実験をしたことがあります．

* https://github.com/mirakc/trace-bridge

TSパケットレベルでメトリックスを取りたい場合には，フィルター機能を使うという方法はあります．tuner-filterなどでTSパケットの統計情報を集られます．

mirakc内部のパイプラインでのパケットロスなど統計情報をログから調べるには，ログレベルをdebugやtraceにして大量のログを出力させる必要があるので，非力なマシン上では難しいかもしれません．そのような場合にはmirakc内部で統計情報を集めるような実装が必要になるだろうと思います．

**Comment by masnagam** [comment]
`code(-9)`は多分`ARIB_STD_B25_ERROR_ECM_PROC_FAILURE`

* https://github.com/stz2012/libarib25/search?q=ARIB_STD_B25_ERROR_ECM_PROC_FAILURE

`proc_ecm_b_cas_card`で失敗するケースは３つなので，このあたりに`printf`を入れれば場所の特定はできるだろうと思います．

* https://github.com/stz2012/libarib25/blob/master/src/b_cas_card.c#L354

**Comment by vroad** [comment]
今日、再起動した後復号化が出来なかったようで、同じような`b25_decode failed (code=-9). fall back to encrypted recording.` のログの後、再生できないファイルが出来てました。

tspacketchkで同時間帯のファイルや、昨夜録画されたもので再生出来なかったものをいくつか見るとどのファイルもこのようにscramblingがあるので、「recpt1で録画は続いているが、再生できないファイルが出来る」のはこれが原因ですね。

```
   pid      packets         drop        error   scrambling
-----------------------------------------------------------
0x0000        68401            0            0            0
0x0001          684            0            0            0
0x0010         6840            0            0            0
0x0011         3420            0            0            0
0x0012       386603            0            0            0
0x0014         1368            0            0            0
0x0024         6840            0            0            0
0x0029          137            0            0            0
0x0060        68400            0            0            0
0x0100     54906912            0            0     54906912
0x0110       912003            0            0       912003
0x0130        12628            0            0        12628
0x0138         6780            0            0            0
0x01f0       136800            0            0            0
0x01ff       118270            0            0            0
0x0511       386098            0            0       386098
0x0512       145405            0            0            0
0x0513       153740            0            0            0
0x0611      8121170            0            0            0
0x0612      3123398            0            0            0
0x0613       114349            0            0            0
0x061f         8320            0            0            0
0x0711         6841            0            0            0
-----------------------------------------------------------
           68695407            0            0     56217641

            drop+error = 0
         syncbyte lost = 0
              duration = 01:53:59.96 (68695407 packets, 12914736516 byte)
            Check Time = 2.2 sec     (5911.75 Mbyte/sec)
```

```
ERROR mirakc_core::timeshift: nhke: Stopped recording due to some accident, reactivation count reached the maximum number
```
こちらはまた別に原因ありそうですが。

> proc_ecm_b_cas_cardで失敗するケースは３つなので，このあたりにprintfを入れれば場所の特定はできるだろうと思います．

この関数の中のどれかだとして、それによって対処は変わってくるでしょうか？
ちょっと見ただけでは、それぞれどういう理由での失敗なのか分からないですね。
再起動時に使えたり、使えなかったりするので、カードの接触不良かと思っていました。

**Comment by vroad** [comment]
`ERROR mirakc_core::timeshift: nhke: Stopped recording due to some accident, reactivation count reached the maximum number`

もログにありました。もしかして、放送再開しても止まったままですか？

**Comment by masnagam** [comment]
> それによって対処は変わってくるでしょうか？

可能性はあります．

実装者ではないので推測にすぎませんが，

* B_CAS_CARD_ERROR_INVALID_PARAMETER
    * このモジュールの初期化ミスによるエラーなので，今回のケースはこれではない
* B_CAS_CARD_ERROR_NOT_INITIALIZED
    * このモジュールの初期化時に何ならのエラーが発生し`card`が0に
    * 初期化処理の問題なので，これなら他のところでもエラーになりそうな気がする（ので，これではいはず）
* B_CAS_CARD_ERROR_TRANSMIT_FAILED
    * `while`ループの処理でエラー
    * 多分これ

`SCardTransmit`などはpcscライブラリーが提供している関数なので，多分カード関係の問題だと思われます．

mirakcとは直接関係がないので，これ以上の解析はご自身で行ってください．

> nhkeは夜は放送休止するので

私の地域ではこの間も録画を続けています．夜中なのでapiを呼び出したことはありませんが，多分trueです．別の地域では状況が異なるかもしれません．

放送休止時にTSパケットの送出を停止するようなチャンネルだとレコーダーは停止します．

> 放送再開しても止まったままですか？

止まったままです．mirakc自体の再起動が必要です．

すべてのレコーダーが止まったら再起動するような実装も可能かもしれませんが，現時点ではそのようにはなっていません．

**Comment by masnagam** [comment]
```
INFO mirakc_core::timeshift: nhke: Record#63C02778: Started: 2023-01-13 00:30:00 +09:00@160550714960: 放送休止
```

nhkeで問題が発生している番組は放送休止ですが，同じものを私の環境では問題なく記録しています．

可能性としては

1. TSパケットの送出状況に地域差があり，vroadさんの地域では実際に送出されていない
2. TSパケットは送出されているが，ドライバーもしくはチューナーコマンドが正しく動作せず，mirakcにTSパケットを供給できなくなっている

のどちらかだと思われます．こちらでは確認ができなので，ご自身で問題の切り分けを行ってください．

**Comment by vroad** [comment]
> 止まったままです．mirakc自体の再起動が必要です．

とのことですが、放送再開したら再度録画開始してますね。
このissueのタイトルのエラーメッセージがログに記録されても問題はなく、
実際起きた問題は録画が暗号化されたままになってしまった事が原因で、このエラーメッセージは無関係そうです。

再開時にカードを読み取れないと録画が暗号化されたままになりそうですが、その状況への対処は自分で考えてみます。
過去の暗号化されたままの録画も復号すれば視聴可能になるかもしれません。

放送休止すると、`Cannot tune to the specified channel: /dev/pxmlt5video2` のエラーが出てrecpt1が動作していませんでした。

> * TSパケットの送出状況に地域差があり，vroadさんの地域では実際に送出されていない
> * TSパケットは送出されているが，ドライバーもしくはチューナーコマンドが正しく動作せず，mirakcにTSパケットを供給できなくなっている

もし本当に送出されていないのであれば、他の機器を使っても視聴できないのでそれで判定できそうです。

`nhke:` や `kbs:` でjournalctlをgrepすると放送再開後にちゃんと録画が再開されているのが分かります。

```
Jan 17 01:19:25 mirakc-start[2661]: 2023-01-17T01:19:25.345235+09:00 ERROR mirakc_core::timeshift: nhke: Stopped recording due to some accident, reactivation count reached the maximum number
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.602748+09:00  INFO mirakc_core::timeshift: nhke: Service#7FD17FD108080000 is available, activate
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.602818+09:00  INFO mirakc_core::timeshift: nhke: Start activation
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.606946+09:00 DEBUG mirakc_core::timeshift: nhke: Activation finished successfully
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.615164+09:00  INFO mirakc_core::timeshift: nhke: Started recording
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.615284+09:00 DEBUG mirakc_core::timeshift: nhke: Removed the sentinel point 2023-01-17 00:28:37.742 +09:00@672563200000
Jan 17 06:01:22 mirakc-start[2661]: 2023-01-17T06:01:22.776910+09:00 DEBUG mirakc_core::timeshift: nhke: Chunk#4105: Timestamp: 2023-01-17 06:01:23 +09:00
Jan 17 06:01:22 mirakc-start[2661]: 2023-01-17T06:01:22.780392+09:00  INFO mirakc_core::timeshift: nhke: Record#63C5BB23: Started: 2023-01-17 06:01:23 +09:00@672563200000: 旅するためのフランス語（１４）いろいろ尋ねて温まろうJan 17 06:02:43 mirakc-start[2661]: 2023-01-17T06:02:43.817538+09:00 DEBUG mirakc_core::timeshift: nhke: Record#63C5BB23: Updated: 2023-01-17 06:02:43.636 +09:00@672727040000: 旅するためのフランス語（１４）いろいろ尋ねて温まろうJan 17 06:02:43 mirakc-start[2661]: 2023-01-17T06:02:43.818017+09:00 DEBUG mirakc_core::timeshift: nhke: Chunk#4106: Timestamp: 2023-01-17 06:02:43.636 +09:00
```

kbsも同様です。

```
Jan 17 03:16:25 mirakc-start[2661]: 2023-01-17T03:16:25.780826+09:00 ERROR mirakc_core::timeshift: kbs: Stopped recording due to some accident, reactivation count reached the maximum number
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.602794+09:00  INFO mirakc_core::timeshift: kbs: Service#7D667D66A4300000 is available, activate
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.603107+09:00  INFO mirakc_core::timeshift: kbs: Start activation
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.606454+09:00 DEBUG mirakc_core::timeshift: kbs: Activation finished successfully
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.615393+09:00  INFO mirakc_core::timeshift: kbs: Started recording
Jan 17 06:01:20 mirakc-start[2661]: 2023-01-17T06:01:20.615456+09:00 DEBUG mirakc_core::timeshift: kbs: Removed the sentinel point 2023-01-17 02:56:16.934 +09:00@766935040000
Jan 17 06:01:24 mirakc-start[2661]: 2023-01-17T06:01:24.645880+09:00 DEBUG mirakc_core::timeshift: kbs: Chunk#4681: Timestamp: 2023-01-17 06:01:25 +09:00
Jan 17 06:01:24 mirakc-start[2661]: 2023-01-17T06:01:24.648841+09:00  INFO mirakc_core::timeshift: kbs: Record#63C5BB25: Started: 2023-01-17 06:01:25 +09:00@766935040000: お買い物プラス　「世界の“！”をお届けします」Jan 17 06:02:47 mirakc-start[2661]: 2023-01-17T06:02:47.809193+09:00 DEBUG mirakc_core::timeshift: kbs: Record#63C5BB25: Updated: 2023-01-17 06:02:47.868 +09:00@767098880000: お買い物プラス　「世界の“！”をお届けします」Jan 17 06:02:47 mirakc-start[2661]: 2023-01-17T06:02:47.809238+09:00 DEBUG mirakc_core::timeshift: kbs: Chunk#4682: Timestamp: 2023-01-17 06:02:47.868 +09:00
Jan 17 06:04:09 mirakc-start[2661]: 2023-01-17T06:04:09.293415+09:00 DEBUG mirakc_core::timeshift: kbs: Record#63C5BB25: Updated: 2023-01-17 06:04:09.471 +09:00@767262720000: お買い物プラス　「世界の“！”をお届けします」
```

**Comment by masnagam** [comment]
> 放送再開したら再度録画開始してますね

ああ，scan-servicesが動いてサービスが更新されると，確かに再起動されますね．

jobs.scan-services.scheduleの設定を見れば，いつ頃再開されるかわかります．
既定値では6時と18時あたりですね．

**Comment by vroad** [comment]
ってことは、少なくともこのissueで書いたタイトルの問題については、実用上はいまのままでも問題ないって事でしょうか？（ログレベルが`ERROR`のメッセージがログに残る事以外は）
仮にもっと早くに再開させたいとすれば、その設定値を調節すれば良さそうですね。

「recpt1 放送休止」で検索すると、放送休止中の場合はチャンネルスキャンしても取得できないという現象であれば他の方も経験してるようです。

https://blog.tsukumijima.net/article/new-bs-channel-settings/

mirakc側としてはドライバーやrecpt1の問題か、アンテナ線が抜けているのか分からないので
recpt1のエラーを見て対処するのは難しいのではと思います。
kbs、nhkeの早朝の時間帯は録画しないようにするか、
または早朝の場合、ログレベルをINFOに下げて別なメッセージをログに記録すれば、エラーが極力ログに残らないようには出来るかもしれないですが、そのような対処ってどうなんでしょうか。
問題発生時にログを見る際ノイズになりそうなので、出来ればERRORとしては記録されないようにしたいです。

Grafanaアラートについては早朝はアラートを送出しないように出来そうです。

https://grafana.com/docs/grafana/next/alerting/manage-notifications/mute-timings/

**Comment by masnagam** [comment]
> 実用上はいまのままでも問題ないって事でしょうか？

「実用上」は利用者の主観なので，私にはなんとも言えません．
少なくとも私個人は，v1の実装でも困難な問題に遭遇したことは（少なくともこれまでは）ありませんでした．

> 仮にもっと早くに再開させたいとすれば、その設定値を調節すれば良さそうですね。

そうですね，それで対処可能だと思います．

> recpt1のエラーを見て対処するのは難しいのではと思います

そうですね，すべての状況ごとにエラーコードが用意されているわけではないので，無理だろうと思います．また，チューナープログラムもrecpt1だけではないので，各チューナーコマンドのエラーコードごとに処理を書くこともありません．

仮に実装するなら，mirakc側でエラーコードを定義し，これに応じて動作をかえるのだろうと思います．ただ，この場合には利用者側でエラーコードの変換をスクリプトファイルなどで行う必要があるため，少し面倒です．多分，実装しないだろう思います．

> そのような対処ってどうなんでしょうか

ログレベルを動的に変更するのは簡単ではありません．mirakc起動時にRUST_LOGを解析するので（tracingという外部モジュールを使っています），環境変数RUST_LOGを実行中に変えたとしても反映されません．多分，多くのソフトウェアで同様の実装になっているだろうと思います．

出力されたログを状況に応じてフィルターするのが一般的かと思います．

> 問題発生時にログを見る際ノイズになりそうなので、出来ればERRORとしては記録されないようにしたいです

一時的であれレコーダーが停止する状況はエラーとして出力されるべきだと考えています．出力されたログを時間帯でフィルターしてください．

**Comment by vroad** [comment]
> 環境変数RUST_LOGを実行中に変えたとしても反映されません．

いえ、ログ全体に影響が出るRUST_LOGを変更するという意味ではなく、録画停止時のエラーメッセージのみ、早朝はERRORではなくINFOとして記録したり、
記録するメッセージ内容を変更するような意味でした。

ただ、そのような変更もしないと書いてるようなので
今のところはこの時間帯のログだけ除外して見ようかと思います。

恐らく他の方もなると思うので、
エラーメッセージに放送休止時もこのエラーになる場合があると記載したり、ドキュメントに書くと良いかもしれません。

> 一時的であれレコーダーが停止する状況はエラーとして出力されるべきだと考えています．出力されたログを時間帯でフィルターしてください．

`jobs.scan-services.schedule`で放送休止後の再開時間をコントールする事は可能かと思いますが、
録画を停止する時間もチャンネルごとに設定する事は現在可能でしょうか？
この機能があれば、あまり見ない時間帯の番組の録画を行わず、ストレージを節約して録画時間を伸ばすのにも使えそうですが、放送休止前に録画を止めてしまえば
放送休止中のエラーを回避することにも繋がるかと思います。

**Comment by masnagam** [comment]
> 記録するメッセージ内容を変更するような意味でした

そういうことでしたか，理解しました．

> ただ、そのような変更もしないと書いてるようなので

そうですね，あまり時間帯でログレベルを変えるような修正はしたくありません．

> エラーメッセージに放送休止時もこのエラーになる場合があると記載したり、ドキュメントに書くと良いかもしれません

そうですね，追記して良いと思います．

> 録画を停止する時間もチャンネルごとに設定する事は現在可能でしょうか

現状，そのような機能はありません．起動すると常に録画し続けます．

一定程度の要望はある機能だと感じます．ただ，私は使わないので，私がすぐに実装することはないだろうと思います．誰か実装すればPRを受け付けます．

**Comment by vroad** [comment]
このissueをcloseする条件はドキュメントの追記にしましょうか？

recpt1がエラーになるのは夜中の遅い時間の事が多く、夜中に視聴できるかはまだ試せてないです。
nhkeについては番組表で放送休止の時間になってもすぐrecpt1がエラーになる訳ではなく、しばらくは通常通り録画されています。

この2つのチャンネルだけ本当に放送が止まってるのかもしれませんし、recpt1やドライバの問題かもしれませんが、既に書いたように、mirakc側が対処は出来ないかと思います。
仮にrecpt1やドライバの問題だったとして、私の現在の知識では問題の修正は難しそうで、当面はこの時間帯にはエラーメッセージの出力は必ずされるものとして
運用で回避するしか無さそうです。

> 現状，そのような機能はありません．起動すると常に録画し続けます．
> 
> 一定程度の要望はある機能だと感じます．ただ，私は使わないので，私がすぐに実装することはないだろうと思います．誰か実装すればPRを受け付けます．

了解です。特定時間帯にエラーになる事から起きる問題は運用で回避可能なので、もし自分で何か作るとすればdropやscramblingになったパケットの統計の方を先に作りたいですね。

> TSパケットレベルでメトリックスを取りたい場合には，フィルター機能を使うという方法はあります．tuner-filterなどでTSパケットの統計情報を集めることが可能です．

もしこれを使った場合、recpt1の標準出力→tuner-filterに指定したコマンド→mirakc側の処理
のようになるかと思うので、recpt1の出力は正常だが、mirakc側の処理やディスクへの書き込みが追いつかずドロップした場合などはtuner-filter側では分からないと思いますが、合ってますでしょうか。
ログに`No space for tuner#3.3.1, drop the chunk`のようなメッセージがあるか見ればdropが起きている事は分かりますが、その場合の統計を取るには別途処理の追加が必要になるかと思います。

**Comment by masnagam** [comment]
> このissueをcloseする条件はドキュメントの追記にしましょうか？

ドキュメントへの追記はそれでよいです．

パケットが供給されていないのかどうかは少し気になりますが，私の環境では調査ができないので，どうしても報告者に調査してもらうしかありません．もし調査する予定があって詳細がわかったら新しいチケットを登録してください．

> nhkeについては番組表で放送休止の時間になってもすぐrecpt1がエラーになる訳ではなく

多分放送休止になってしばらくすると，どこかでパケットの供給が止まるのでしょうね．

> tuner-filter側では分からないと思いますが、合ってますでしょうか

あっています．

ログレベルをtraceにすると大量にログがでますが，mirakc内部のパケットのドロップ状況などがわかります．

* https://github.com/mirakc/mirakc/blob/main/mirakc-core/src/broadcaster.rs#L133

ただ，これは本当に大量にログが出るので，出力されるログをファイルに残したい場合は，ファイルに書き出す前にログをフィルターする必要があります．

人それぞれ考えはあるとは思いますが，内部で統計情報を取るのではなく，必要な情報をすべて出力し，外部プログラムで統計情報にしたほうがよいだろうという考えでそうしていましたが，`dropped_bytes`のように集計後のログを出すか決めかねています．

このような状況なので，mainではログメッセージが変わることがあります．release後にログ統計の実装を行うことをお勧めします．

タイムシフト録画でts-fileに書き出す直前にドロップチェックを行いたい場合には，`config.timeshift.command`を差し替える必要があります．このコマンドにSTDIN経由で供給されるバイト列がTSパケット境界に揃っていない場合，resyncによりいくらかデータが失われます．

* https://github.com/mirakc/mirakc-arib/blob/main/src/packet_source.hh#L140

タイムシフト録画では現状post-filterが使えないので，コマンドを差し替えないといけません．post-filterが使える普通の録画機能やweb streamingならpost-filterでパイプラインの最後でチェックを実行することが可能です．

**Comment by vroad** [comment]
個人的には、mirakc内部のドロップ統計は（他のログと一緒に）標準出力に吐き出して他のプログラムで収集するよりは、APIでアクセス可能にする方が良いと思います。
ドロップのタイミングが分かるように、数分ごとに頻繁に出せば、他のツールを使ってフィルタリングしない限り他のログが埋もれますし、それを避けようとして一定期間の情報をまとめて出すとどのタイミングで起きたか分かりにくいかと思います。
出来れば、他のツールを併用しなくてもjournalctlだけでログは見られるようにしたいです。

APIとして外からアクセス可能にする場合、どのような形で出すのかが問題になるかと思いますが、
タイムシフト録画のdata-fileを書き込む際にこれまでの総ドロップ数を一緒に書き込み、 `/api/timeshift` でアクセスできるようにすれば[json_exporter](https://github.com/prometheus-community/json_exporter)でそのまま使えて良いかと思いました。
チャンクサイズが160MBなら、160MB書き込む度に更新されるので、十分細かい時間感覚で統計を取れると思います。

この方式だと、APIでアクセス可能する際、過去のデータをどうアクセス可能にするかを考える必要がないので実装はシンプルになります。過去のデータへのアクセスはPrometheusが提供してくれます。
デメリットは、ログに吐く方式と同様、過去の統計を記録するのは監視ツールの役目になるのでユーザーは何らかの監視ツールが必要な事ですが、私は既に導入したので、私にとっては問題ないです。

ログに吐く方式を取るとしても、上述の理由から、標準出力とは別の場所を選べる方が良いと思います。
この場合、journalctlにログローテーションさせられないので、ログローテーションを組み込む必要がありますね。
「mirakc側でログローテーションはしません。別途logrotateを入れてください」でも良いですが。
この場合も、mirakcはJSONLで追記書き込みして、それを別なツールに食わせたりすればPrometheusのような監視ツールに取り込めそうです。

既存実装でtraceされるのはドロップ数だけで、tspacketchkで言うscramblingになっているパケットの統計はまだありませんよね？

mirakcの統計については #15 で話を続けた方が良いかと思いましたが、既にある@masnagamさんのコメントは英語です。日本語コメント混じっても問題ないですか？
英語でまったく書けないことは無いですが、日本語の方が読み書きしやすいです。

**Comment by masnagam** [comment]
> 日本語コメント混じっても問題ないですか？

問題ありません．単に私が英語で書く機会を増やすためだけに英語で記述しています（そうしないと上達しないので）．

ログ出力には[tracing](https://github.com/tokio-rs/tracing)を使っていますが，これはログというよりはイベントを記録する機能を提供しており，それをmirakcでは文字列化してログ出力しています．これを他のプログラムのstdoutにpipeすることを検討していましたが，後述の

[tracing-subscriber](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/)という関連モジュールがあり，ここでイベントをフィルタリングしたり統計情報化したりします．

**Comment by masnagam** [comment]
mirakc/dekiru-mirakc@ea55972adb3d463102f0b66c708531fefc4a2728 で追記しました

**Comment by vroad** [comment]
> 対象サービスが放送波から削除されたら，`TimeshiftManager::recorders`から削除
> * `/api/timeshift`の一覧にも表示されなくなる

`/api/timeshift`の一覧の
name、duration、recordingの値はGrafanaのパネルで表示したりアラートに使っているのですが、それも消えるでしょうか？

> rust側の修正がまだなら少し待ってもらったほうがよいかもしれません．

rust側は特にまだ何も手を付けてないので、それは大丈夫です。

**Comment by masnagam** [comment]
> それも消えるでしょうか？

~~消えます．放送波から消えるということは，再編などでそのチャンネル自体がなくなることを意味します．~~
と考えていたのですが，消してしまうと今までのレコードを参照できなくなってしまうので，やめることにします．
